# This file is auto-generated by the CI build pipeline.
# Do not edit manually — changes will be overwritten on release builds.
# For local development, edit this value manually if needed.
__version__ = "dev"
